Scripting with tmux
Config file organization, docs, and ccdTerm development in the TMux sandbox

diff --git a/Sandbox/TMux/ccdTerm b/Sandbox/TMux/ccdTerm
--- a/Sandbox/TMux/ccdTerm
+++ b/Sandbox/TMux/ccdTerm
@@ -1,9 +1,27 @@
 #!/bin/bash
 
 tmuxID="ccdTerm"
-modsHost="${HOSTNAME^^}"
-modsChan="red"
-modsID="${modsHost} Red"
+
+# LBTO Public executable path
+
+modsDir="/lbt/lbto/mods"
+configDir="/lbt/lbto/mods/.config"
+
+# Which MODS ccd host are we running on?
+
+modsHost="${HOSTNAME}"
+
+if [[ "$modsHost" == "mods1blue" || "$modsHost" == "mods1red" || "$modsHost" == "mods2blue" || "$modsHost" == "mods2rede" ]]; then
+    modsID=${modsHost:0:6}   # like mods1b, used by azcam
+    modsChan=${modsHost:5:${#modsHost}} # blue or red, for config files
+    modsInst=${modsHost:0:5} 
+    modsInst=${modsInst^^}   # capitalized MODS instance (MODS1 or MODS2)
+    modsName="${modsInst} ${modsChan^}" # for tmux session
+
+else
+    echo "ERROR: you cannot run $tmuxID on host $modsHost"
+    exit 1
+fi
 
 # Check if the session already exists
 
@@ -12,11 +30,11 @@ tmux has-session -t $tmuxID 2>/dev/null
 if [ $? != 0 ]; then
   # Create a new detached session
 
-  tmux -f ~/.tmux.conf.$modsChan new-session -d -s $tmuxID
+  tmux -f ${configDir}/tmux_${modsChan}.conf new-session -d -s $tmuxID
 
   # Create a new window (if needed) and name it
 
-  tmux new-window -t $tmuxID:1 -n "${modsID} CCD Controller Admin"
+  tmux new-window -t $tmuxID:1 -n "${modsName} CCD Admin"
 
   # Split the window into panes (optional, adjust as needed)
 
