public script work
added restriction to pokeMODSn to only allow by user "lbto"

diff --git a/Scripts/Public/pokeMODS2 b/Scripts/Public/pokeMODS2
--- a/Scripts/Public/pokeMODS2
+++ b/Scripts/Public/pokeMODS2
@@ -8,6 +8,13 @@
 # Updated: 2025 Oct 14 - Archon controller updates [rwp/osu]
 #
 
+set user=`echo $USER | tr '[:upper:]' '[:lower:]'`
+if ("${user}" != "lbto") then
+   printf "ERROR: User '${user}' is not permitted to run this program.\n"
+   printf "       Please ask your ISP for assistance.\n"
+   exit 1
+endif
+
 set errCount = 0
 echo "Poking MODS2 Mechanisms..."
 echo "Common focal plane:"
